// Generated by tools/build_catalog.py: do not edit by hand.
// To add a worksheet, fill in its <meta> tags and run the script again (see CLAUDE.md).
window.CATALOG = [
  {
    "file": "coloriage-animaux-australie.html",
    "title": "Animaux d’Australie à colorier",
    "description": "Quatre animaux d’Australie à colorier : le wallaby, le koala, le requin et le dauphin.",
    "subject": "Arts visuels",
    "levels": [
      "4P"
    ],
    "keywords": [
      "coloriage",
      "animaux",
      "Australie",
      "wallaby",
      "koala",
      "requin",
      "dauphin"
    ],
    "added": "2026-09-29",
    "pages": 1,
    "answer_key": false,
    "randomized": false
  },
  {
    "file": "exercices-alphabet-voyelles.html",
    "title": "L’alphabet et les voyelles",
    "description": "Trouver la lettre d’avant et d’après, entourer les voyelles, ranger des mots dans l’ordre alphabétique, avec un défi pour finir.",
    "subject": "Français",
    "levels": [
      "4P"
    ],
    "keywords": [
      "alphabet",
      "lettres",
      "voyelles",
      "consonnes",
      "ordre alphabétique"
    ],
    "added": "2026-09-30",
    "pages": 1,
    "answer_key": true,
    "randomized": true
  },
  {
    "file": "exercices-phrases-mots.html",
    "title": "Les mots et les phrases",
    "description": "Remettre en ordre les mots d’une phrase, corriger des mots inversés et trouver l’intrus en comptant les lettres.",
    "subject": "Français",
    "levels": [
      "4P"
    ],
    "keywords": [
      "phrase",
      "mots",
      "ordre des mots",
      "majuscule",
      "point",
      "compter les lettres",
      "intrus"
    ],
    "added": "2026-10-03",
    "pages": 3,
    "answer_key": true,
    "randomized": true
  },
  {
    "file": "formes-geometriques.html",
    "title": "Les formes géométriques",
    "description": "Observer six figures et écrire leur nom : triangle, losange, rectangle, carré, forme convexe et forme non-convexe.",
    "subject": "Mathématiques",
    "levels": [
      "4P"
    ],
    "keywords": [
      "géométrie",
      "formes",
      "figures",
      "triangle",
      "carré",
      "rectangle",
      "losange",
      "convexe",
      "non-convexe"
    ],
    "added": "2026-09-29",
    "pages": 1,
    "answer_key": false,
    "randomized": false
  },
  {
    "file": "losanges.html",
    "title": "Les losanges",
    "description": "Reconnaître six losanges (carré, aplati, debout, penché, couché, fin) grâce au codage des côtés de même longueur.",
    "subject": "Mathématiques",
    "levels": [
      "4P"
    ],
    "keywords": [
      "géométrie",
      "losange",
      "côtés égaux",
      "angle droit",
      "codage"
    ],
    "added": "2026-09-30",
    "pages": 1,
    "answer_key": false,
    "randomized": false
  },
  {
    "file": "triangles.html",
    "title": "Les triangles",
    "description": "Nommer six triangles (équilatéral, isocèle, rectangle, obtusangle…) en lisant le codage des côtés et des angles.",
    "subject": "Mathématiques",
    "levels": [
      "4P"
    ],
    "keywords": [
      "géométrie",
      "triangle",
      "isocèle",
      "équilatéral",
      "rectangle",
      "obtusangle",
      "quelconque",
      "angle droit"
    ],
    "added": "2026-09-30",
    "pages": 1,
    "answer_key": false,
    "randomized": false
  },
  {
    "file": "arbres.html",
    "title": "L’arbre et la forêt",
    "description": "Quatre exercices sur deux pages : les parties de l’arbre, conifère ou feuillu, la feuille et le fruit, vivant ou non vivant.",
    "subject": "Sciences de la nature",
    "levels": [
      "4P"
    ],
    "keywords": [
      "arbre",
      "forêt",
      "conifère",
      "feuillu",
      "feuille",
      "fruit",
      "écorce",
      "racines",
      "vivant",
      "non vivant"
    ],
    "added": "2026-10-02",
    "pages": 2,
    "answer_key": true,
    "randomized": false
  }
];
